---
title: "September 2020"
output:
  html_document:
    toc: true
    toc_depth: 3
    toc_float: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r include=FALSE}
library(kableExtra)
library(knitr)
library(tidyverse)
library(stringr)
library(DT)
library(lubridate)
library(scales)
library(tidyr)
library(tidyr)
library(plotly)
library(ggplot2)

kumulatif_sep_20 <- read.csv("https://docs.google.com/spreadsheets/d/e/2PACX-1vQUYsfUgVYlVMpSWUj0U20y7GjAFgdPdNQhMxry-_31ekA_9i1KIlNHoiDgI0H0N1ady3g2SGQUICBU/pub?gid=1958899369&single=true&output=csv"
)
kumulatif_sep_20$average.target <- as.numeric(gsub("[Rp.]","", kumulatif_sep_20$average.target))
kumulatif_sep_20$kumulatif.target <- as.numeric(gsub("[Rp.]","", kumulatif_sep_20$kumulatif.target))
kumulatif_sep_20$realisasi <- as.numeric(gsub("[Rp.]","", kumulatif_sep_20$realisasi))
kumulatif_sep_20$kumulatif.realisasi <- as.numeric(gsub("[Rp.]","", kumulatif_sep_20$kumulatif.realisasi))

#mengubah format tanggal
kumulatif_sep_20 <- kumulatif_sep_20 %>% mutate(tanggal2 =as.Date(tanggal, format= '%d/%m/%y'))

str(kumulatif_sep_20)

#Mengubah nilai NA jadi ""
kumulatif_sep_20 %>% replace(., is.na(.), "")
                

```

## Target dan Realisasi Kumulatif



```{r graf_line, echo=FALSE, warning=FALSE}
ggplot(data=kumulatif_sep_20,
            aes(x=tanggal2)) +
  geom_line(aes(y = kumulatif.target), color = "darkred", size = 1, alpha=0.3) +
  geom_line(aes(y = kumulatif.realisasi), color = "steelblue", size = 1, alpha=0.3) +
  geom_point(aes(y = kumulatif.realisasi), color = "steelblue", size=2, alpha=0.8) +
  geom_point(aes(y = kumulatif.target), color = "red", size=2, alpha=0.8) +
  xlab("tanggal") +
  ylab("Rupiah") +
  ggtitle("Realisasi Sparepart Kumulatif September 2020") +
  scale_y_continuous(name = "Milyar Rupiah", limits = c(0, 7000000000), labels = scales::comma)
  
  #scale_x_discrete(name = "Tanggal", limits = c(1:31))
#theme(legend.position = c(0.25, 0.9),
#legend.direction = "horizontal")
```

Note that the `echo = FALSE` parameter was added to the code chunk to prevent printing of the R code that generated the plot.
$~$
$~$  
    
    
 
## Top 10 Material Used

```{r top_10_spare, echo=FALSE}
library(dplyr)
rl_sep_20 <- read.csv("https://docs.google.com/spreadsheets/d/e/2PACX-1vQUYsfUgVYlVMpSWUj0U20y7GjAFgdPdNQhMxry-_31ekA_9i1KIlNHoiDgI0H0N1ady3g2SGQUICBU/pub?gid=0&single=true&output=csv")

rl_sep_20$Quantity <- as.numeric(rl_sep_20$Quantity)
rl_sep_20$Amount.in.LC <- as.numeric(rl_sep_20$Amount.in.LC)


top_spare <- rl_sep_20 %>%
  group_by(Material,Description, Base.Unit) %>%
  summarize(
    Qty = sum(Quantity, na.rm = TRUE),
    Amount = sum(Amount.in.LC, na.rm = TRUE)
  ) %>%
  arrange(desc(Amount)) %>%
  top_n(10)
datatable(top_spare) %>% formatCurrency('Amount', currency = "Rp", interval = 3, mark = ",", digits = 2, dec.mark = getOption("OutDec"), before = TRUE)
```
  
  
$~$
$~$
  

    
## Top 10 Unit Kerja

```{r top_10_uk, echo=FALSE}


top_uk <- rl_sep_20 %>%
  group_by(NAMA.SEKSI.PG) %>%
  summarize(
    Amount = sum(Amount.in.LC, na.rm = TRUE)
  ) %>%
  arrange(desc(Amount)) 
 
datatable(top_uk) %>% formatCurrency('Amount', currency = "Rp", interval = 3, mark = ",", digits = 2, dec.mark = getOption("OutDec"), before = TRUE)
```
$~$
$~$

## List Material per Unit Kerja
```{r list_mat_perUK, echo=FALSE}


list_mat_uk <- rl_sep_20 %>%
  group_by(CORRECTED.DESC.CC.PG, Order, Functional.loc., DESKRIPSI.KEGIATAN,  Material,Description, Base.Unit) %>%
  summarize(
    Qty = sum(Quantity, na.rm = TRUE),
    Amount = sum(Amount.in.LC, na.rm = TRUE)
  ) %>%
  arrange(desc(Amount)) %>%
  rename(Unit_Kerja = CORRECTED.DESC.CC.PG,
         FUNLOC = Functional.loc.,
         Order_desc = DESKRIPSI.KEGIATAN,
         Unit = Base.Unit)
 
datatable(list_mat_uk, extensions = 'Buttons',
            options = list(dom = 'Blfrtip',
                           buttons = c('copy', 'csv', 'excel', 'pdf', 'print'),
                           lengthMenu = list(c(10,25,50,-1),
                                             c(10,25,50,"All")))) #%>% formatCurrency('Amount', currency = "Rp", interval = 3, mark = ",", digits = 2, dec.mark = getOption("OutDec"), before = TRUE)
```

$~$

## SUMMARY AJUAN, TARGET, DAN REALISASI 


```{r summary_perUK, echo=FALSE}

db_sep <- read.csv("https://docs.google.com/spreadsheets/d/e/2PACX-1vRluAGgaJnIMXTovQBTozWFZYeVroT8cgZwmH6DdmiGBJ3bKbR_82Y0zJgimGh-HqOIpZVP7x3OgIGU/pub?gid=0&single=true&output=csv")

db_sep$TOTAL.BIAYA <- as.numeric(as.character(db_sep$TOTAL.BIAYA))
db_sep$TARGET.AJUAN <- as.numeric(as.character(db_sep$TARGET.AJUAN))
db_sep$Realisasi <- as.numeric(as.character(db_sep$Realisasi))

db_sep <- db_sep %>% mutate(Ajuan = TOTAL.BIAYA,
                            Target = TARGET.AJUAN,
                            REALISASI = Realisasi)

db_09_20<-gather(db_sep, kategori, jumlah, Ajuan:REALISASI)

bar_db_09_20 <- db_09_20 %>% group_by(kategori) %>%
                summarize( tot = sum(jumlah, na.rm = TRUE)) 

p<-ggplot(bar_db_09_20, aes(x=kategori, y=tot, fill=kategori)) +
  geom_bar(stat="identity")+theme_minimal() +

xlab("Kategori") +
  ylab("Rupiah") +
  ggtitle("SUMMARY BIAYA MATERIAL SEPTEMBER") +
  scale_y_continuous(name = "Milyar Rupiah", limits = c(0, 12000000000), labels = scales::comma) +
  geom_text(aes(label=(tot/1000000000)), position=position_dodge(width=0.9), vjust=-0.25)
   

p


```
$~$
$~$



## Ajuan Sparepart Per UK

```{r ajuan_perUK, echo=FALSE}
aj_db_sep <- db_sep %>% 
  filter(PLANT == 9) %>%
  select(NAMA.SEKSI.PLANNER, EQUIP, RENCANA.KEGIATAN, STOCK.NO., NAMA.MATERIAL...JASA, SAT, QTY, TOTAL.BIAYA ) %>%
  rename(Nama_UK = NAMA.SEKSI.PLANNER,
         Kegiatan = RENCANA.KEGIATAN,
         No.Stock = STOCK.NO.,
         Matl.Descriptions = NAMA.MATERIAL...JASA,
         Total = TOTAL.BIAYA)
  

datatable(aj_db_sep, extensions = 'Buttons',
            options = list(dom = 'Blfrtip',
                           buttons = c('copy', 'csv', 'excel', 'pdf', 'print'),
                           lengthMenu = list(c(10,25,50,-1),
                                             c(10,25,50,"All"))))



```

